### ISSUE TITLE
git recent-branches fails with TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by ofourdan** [whot/git-branch-tools#8]
`git recent-branches` fails with:

```
$ git recent-branches
ERROR:root:Date is in the future?
Traceback (most recent call last):
  File "/usr/libexec/git-core/git-recent-branches", line 294, in <module>
    walk_reflog(args, repo)
  File "/usr/libexec/git-core/git-recent-branches", line 245, in walk_reflog
    print("{:<45} {:<20} last commit {:<15}".format(branch, l.reltime, l.reltime_commit))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```

The date/time of my system hasn't changed since I modified the branches though.

**Comment by whot** [comment]
fixed now, I think, or at least it no longer crashes. no idea why the timestamp was in the future to begin with though.
